public class HelloJi{
    private String greeting = 'Hello World';
    
    public String publicGreeting = 'My public greeting var';
    
   // private String goodMorning= 'Good Morning';
   // private String goodAfternoon= 'Good Afternoon';
   // private String goodEvening= 'Good Evening';
    
    
    /*
     public void printGreeting() {
        System.debug();
    }
    
    
   public void printGoodMorning() {
        System.debug(goodMorning);
    }
    
   public void printGoodAfternoon() {
        System.debug(goodAfternoon);
    }
    
   public void printGoodEvening() {
        System.debug(goodEvening);
    }
    
    */
    
    public void printMsg(String msg){
         System.debug(msg);
    }
    
    
    
    
}